---
# kubectl expose pod -n lakehouse --type=ClusterIP --cluster-ip=None jupyter-thiago --port=2222 --target-port=2222
apiVersion: v1
kind: Service
metadata:
  name: jupyter-thiago
spec:
  type: ClusterIP
  clusterIP: "None"
  selector:
    app: jupyter
    hub.jupyter.org/username: thiago
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 2222